id: https://example.org/knownet # change this later to id: https://github.com/myusername/my-project/course-profile
name: KnownetApplicationProfile
prefixes:
  ocds: http://data.tbfy.eu/ontology/ocds#
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  org: http://www.w3.org/ns/org# 
  dcterms: http://purl.org/dc/terms/
  xsd: http://www.w3.org/2001/XMLSchema# 
  ext: http://example.org/extensions/

default_prefix: ocds

classes:
  # --- CLASS 1: CONTRACT ---
  Contract:
    class_uri: ocds:Contract
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      contract_id:
        identifier: true
        slot_uri: ocds:contractId
        required: true
        range: string

      signing_date:
        slot_uri: ocds:dateContractSigned
        required: true
        range: datetime

      initial_value:
        slot_uri: ext:initialContractValue
        required: true
        range: decimal

      final_value:
        slot_uri: ext:finalContractValue
        required: true
        range: decimal

      execution_deadline:
        slot_uri: ext:durationInDays
        required: true
        range: integer

      contract_type:
        slot_uri: ext:contractType
        required: true
        range: string

      causes_deadline_change:
        slot_uri: ext:causesDeadlineChange
        range: string

      causes_price_change:
        slot_uri: ext:causesPriceChange
        range: string
    

  # --- CLASS 2: TENDER ---
  Tender:
    class_uri: ocds:Tender
    
    # 1. Attributes (Data Properties defined locally)
    attributes:
      tender_id:
        identifier: true
        slot_uri: ocds:tenderId
        required: true
        range: string

      numberOfTenderers:
        slot_uri: ocds:numberOfTenderers
        range: integer

      # procurement_method:
      #   slot_uri: ocds:procurementMethod
      #   required: true
      #   range: string

      procedure_type:
        slot_uri: ext:procedureType
        required: true
        range: string

      publication_date:
        slot_uri: ext:dateTenderPublished
        range: datetime

      close_date:
        slot_uri: ext:dateTenderClosed
        range: datetime

      environmental_criteria:
        slot_uri: ext:environmentalCriteria
        range: boolean

      material_criteria:
        slot_uri: ext:materialCriteria
        range: boolean

      centralized_procedure:
        slot_uri: ext:centralizedProcedure
        range: boolean

    # 2. Slots (Object Properties / Links to other classes)
    slots:
      - awardsContract

# --- GLOBAL SLOTS (Object Properties Only) ---
slots:
  awardsContract:
    slot_uri: ext:awardsContract    
    range: Contract
    required: true
    inlined: false